// tide design system — public entry.
// See CONVENTIONS.md for the authoring + doc contract.
export { Avatar, type AvatarSize } from "./Avatar";
export { AvatarGroup, type AvatarGroupMember } from "./AvatarGroup";
export { TokenChip } from "./TokenChip";
export { TokenIcon } from "./TokenIcon";
export { ReactionBar, type Reaction } from "./ReactionBar";
export { FollowButton } from "./FollowButton";
export { Lane, type LaneOption } from "./Lane";
export { SocialProofChip } from "./SocialProofChip";
export { PostCard, type PostKind } from "./PostCard";
export { Sheet } from "./Sheet";
export { CommentThread, type Comment } from "./CommentThread";
export { Onboarding, type HandleAvailability } from "./Onboarding";
export { Button, type ButtonVariant, type ButtonSize } from "./Button";
export { IconButton } from "./IconButton";
export { Badge, type BadgeTone } from "./Badge";
export { Input } from "./Input";
export { Dialog } from "./Dialog";
export { Menu, type MenuItem } from "./Menu";
export { Switch } from "./Switch";
export { Checkbox } from "./Checkbox";
export { Select, type SelectOption } from "./Select";
export { Tabs, type Tab } from "./Tabs";
export { ToastProvider, useToast, type ToastTone } from "./Toast";
export { Divider } from "./Divider";
export { EmptyState } from "./EmptyState";
export { Skeleton, SectionSkeleton } from "./Skeleton";
export { Tooltip } from "./Tooltip";
export { ID_HUES, hueFor, hueGradient, type IdHue } from "./identity";
